/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * @summary Get an airline by ICAO code
 */
export const getAirlinePathIcaoRegExp = new RegExp("^[A-Za-z0-9]{3}$")

export const GetAirlineParams = zod.object({
  icao: zod
    .string()
    .regex(getAirlinePathIcaoRegExp)
    .describe("ICAO airline designator."),
})

export const GetAirlineResponse = zod.object({
  callsign: zod.string().optional(),
  country: zod.string().optional(),
  iata: zod.string().optional(),
  icao: zod.string(),
  name: zod.string(),
})
