/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import type { Airline, ErrorModel } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const getGetAirlineUrl = (icao: string) => {
  return `/airlines/${icao}`
}

/**
 * @summary Get an airline by ICAO code
 */
export const getAirline = async (
  icao: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<Airline> => {
  return bffFetch<Airline>(getGetAirlineUrl(icao), {
    ...options,
    method: "GET",
  })
}

export const getGetAirlineInfiniteQueryKey = (icao: string) => {
  return ["infinite", `/airlines/${icao}`] as const
}

export const getGetAirlineQueryKey = (icao: string) => {
  return [`/airlines/${icao}`] as const
}

export const getGetAirlineInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAirline>>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAirlineInfiniteQueryKey(icao)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAirline>>> = ({
    signal,
  }) => getAirline(icao, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: icao !== null && icao !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAirline>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAirlineInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAirline>>
>
export type GetAirlineInfiniteQueryError = ErrorModel

export function useGetAirlineInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirline>>>,
  TError = ErrorModel,
>(
  icao: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirline>>,
          TError,
          Awaited<ReturnType<typeof getAirline>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirlineInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirline>>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirline>>,
          TError,
          Awaited<ReturnType<typeof getAirline>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirlineInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirline>>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an airline by ICAO code
 */

export function useGetAirlineInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirline>>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAirlineInfiniteQueryOptions(icao, options)

  const query = useInfiniteQuery(
    queryOptions,
    queryClient
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get an airline by ICAO code
 */
export const prefetchGetAirlineInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  icao: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirline>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetAirlineInfiniteQueryOptions(icao, options)

  await queryClient.prefetchInfiniteQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useGetAirlineInfinite} query
 */
export const invalidateGetAirlineInfinite = async (
  queryClient: QueryClient,
  icao: string,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getGetAirlineInfiniteQueryKey(icao) },
    options
  )

  return queryClient
}

export const getGetAirlineQueryOptions = <
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAirlineQueryKey(icao)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAirline>>> = ({
    signal,
  }) => getAirline(icao, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: icao !== null && icao !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAirline>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAirlineQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAirline>>
>
export type GetAirlineQueryError = ErrorModel

export function useGetAirline<
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  icao: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirline>>,
          TError,
          Awaited<ReturnType<typeof getAirline>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirline<
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirline>>,
          TError,
          Awaited<ReturnType<typeof getAirline>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirline<
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an airline by ICAO code
 */

export function useGetAirline<
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  icao: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAirlineQueryOptions(icao, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get an airline by ICAO code
 */
export const prefetchGetAirlineQuery = async <
  TData = Awaited<ReturnType<typeof getAirline>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  icao: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirline>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetAirlineQueryOptions(icao, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useGetAirline} query
 */
export const invalidateGetAirline = async (
  queryClient: QueryClient,
  icao: string,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getGetAirlineQueryKey(icao) },
    options
  )

  return queryClient
}
