/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * @summary Get service status and upstream budgets
 */
export const GetStatsResponse = zod.object({
  aircraftCount: zod.int(),
  aviationstack: zod.object({
    cap: zod.int(),
    enabled: zod.boolean(),
    period: zod.string().describe("Month in YYYY-MM."),
    used: zod.int(),
  }),
  cache: zod.object({
    l1Entries: zod.int().describe("Entries currently in the in-process tier."),
    l1Hits: zod.int().describe("Hits in the in-process tier."),
    l2Hits: zod.int().describe("Hits in Redis."),
    misses: zod.int().describe("Loads from the source."),
  }),
  poller: zod.object({
    dailyCap: zod
      .int()
      .describe("Requests allowed per UTC day before the poller pauses."),
    intervalSeconds: zod
      .int()
      .describe("Target age of the area viewers are looking at."),
    lastError: zod.string().optional(),
    lastPoll: zod.iso.datetime({ offset: true }).optional(),
    leader: zod.boolean().describe("True when this instance runs the poller."),
    mode: zod
      .enum(["active", "idle", "paused", "follower", "disabled"])
      .describe(
        "Poller state. Active while viewers are connected, idle otherwise, paused when rate limited or over the daily request cap, follower when another instance polls."
      ),
    nextPoll: zod.iso.datetime({ offset: true }).optional(),
    requestsToday: zod
      .int()
      .describe("Upstream requests made since UTC midnight."),
    sweepCells: zod.int().describe("Circles in the background world sweep."),
    viewCells: zod
      .int()
      .describe("Circles currently covering viewer viewports."),
  }),
  snapshotAgeSeconds: zod.int(),
  snapshotTime: zod.iso.datetime({ offset: true }).optional(),
  stale: zod
    .boolean()
    .describe("True when the snapshot is older than the freshness limit."),
  version: zod.string(),
  viewers: zod.int().describe("Open live connections on this instance."),
})
