/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * Current positions from the latest snapshot. When more than limit aircraft are inside the box the result is thinned to a stable subset.
 * @summary List aircraft in a bounding box
 */
export const listAircraftQueryWestDefault = -180
export const listAircraftQueryWestMin = -180
export const listAircraftQueryWestMax = 180

export const listAircraftQuerySouthDefault = -90
export const listAircraftQuerySouthMin = -90
export const listAircraftQuerySouthMax = 90

export const listAircraftQueryEastDefault = 180
export const listAircraftQueryEastMin = -180
export const listAircraftQueryEastMax = 180

export const listAircraftQueryNorthDefault = 90
export const listAircraftQueryNorthMin = -90
export const listAircraftQueryNorthMax = 90

export const listAircraftQueryLimitDefault = 1500
export const listAircraftQueryLimitMax = 3000

export const ListAircraftQueryParams = zod.object({
  west: zod
    .number()
    .min(listAircraftQueryWestMin)
    .max(listAircraftQueryWestMax)
    .default(listAircraftQueryWestDefault)
    .describe(
      "Western edge in degrees. Greater than east when the box crosses the antimeridian."
    ),
  south: zod
    .number()
    .min(listAircraftQuerySouthMin)
    .max(listAircraftQuerySouthMax)
    .default(listAircraftQuerySouthDefault)
    .describe("Southern edge in degrees."),
  east: zod
    .number()
    .min(listAircraftQueryEastMin)
    .max(listAircraftQueryEastMax)
    .default(listAircraftQueryEastDefault)
    .describe("Eastern edge in degrees."),
  north: zod
    .number()
    .min(listAircraftQueryNorthMin)
    .max(listAircraftQueryNorthMax)
    .default(listAircraftQueryNorthDefault)
    .describe("Northern edge in degrees."),
  limit: zod
    .int()
    .min(1)
    .max(listAircraftQueryLimitMax)
    .default(listAircraftQueryLimitDefault)
    .describe("Maximum aircraft to return."),
})

export const listAircraftResponseAircraftItemLatMin = -90
export const listAircraftResponseAircraftItemLatMax = 90

export const listAircraftResponseAircraftItemLonMin = -180
export const listAircraftResponseAircraftItemLonMax = 180

export const ListAircraftResponse = zod.object({
  ageSeconds: zod
    .int()
    .describe("Seconds between the snapshot time and the response."),
  aircraft: zod
    .array(
      zod.object({
        baroAltM: zod
          .number()
          .optional()
          .describe("Barometric altitude in metres."),
        callsign: zod
          .string()
          .optional()
          .describe("Callsign as broadcast, trimmed."),
        category: zod
          .enum([
            "unknown",
            "light",
            "small",
            "large",
            "high_vortex_large",
            "heavy",
            "high_performance",
            "rotorcraft",
            "glider",
            "lighter_than_air",
            "parachutist",
            "ultralight",
            "uav",
            "space",
            "emergency_surface",
            "service_surface",
            "obstacle",
          ])
          .describe("ADS-B emitter category."),
        country: zod
          .string()
          .optional()
          .describe("Country of registration inferred from the address."),
        geoAltM: zod
          .number()
          .optional()
          .describe("Geometric altitude in metres."),
        headingDeg: zod
          .number()
          .optional()
          .describe("True track in degrees clockwise from north."),
        icao24: zod.string().describe("Mode S address, lower-case hex."),
        lastContact: zod.iso
          .datetime({ offset: true })
          .describe("Time of the last message received from the aircraft."),
        lat: zod
          .number()
          .min(listAircraftResponseAircraftItemLatMin)
          .max(listAircraftResponseAircraftItemLatMax)
          .describe("WGS-84 latitude in degrees."),
        lon: zod
          .number()
          .min(listAircraftResponseAircraftItemLonMin)
          .max(listAircraftResponseAircraftItemLonMax)
          .describe("WGS-84 longitude in degrees."),
        onGround: zod
          .boolean()
          .describe("True when the aircraft reports being on the ground."),
        positionAt: zod.iso
          .datetime({ offset: true })
          .describe("Time of the last position report."),
        source: zod
          .enum(["adsb", "asterix", "mlat", "flarm", "unknown"])
          .describe("Surveillance technology that produced the position."),
        squawk: zod.string().optional().describe("Transponder code."),
        velocityMs: zod
          .number()
          .optional()
          .describe("Ground speed in metres per second."),
        vertRateMs: zod
          .number()
          .optional()
          .describe(
            "Vertical rate in metres per second, negative when descending."
          ),
      })
    )
    .nullable(),
  count: zod.int().describe("Aircraft returned."),
  stale: zod
    .boolean()
    .describe(
      "True when the snapshot is older than the freshness limit, for example while the poller is out of credits."
    ),
  time: zod.iso.datetime({ offset: true }).describe("Snapshot time."),
  total: zod.int().describe("Aircraft inside the bounds before thinning."),
})

/**
 * @summary Get one aircraft with its recent trail
 */
export const getAircraftPathIcao24RegExp = new RegExp("^[0-9a-fA-F]{6}$")

export const GetAircraftParams = zod.object({
  icao24: zod
    .string()
    .regex(getAircraftPathIcao24RegExp)
    .describe("Mode S address as six hex digits."),
})

export const getAircraftResponseStateLatMin = -90
export const getAircraftResponseStateLatMax = 90

export const getAircraftResponseStateLonMin = -180
export const getAircraftResponseStateLonMax = 180

export const GetAircraftResponse = zod.object({
  icao24: zod.string(),
  info: zod
    .object({
      icao24: zod.string(),
      manufacturer: zod.string().optional(),
      model: zod.string().optional(),
      operator: zod.string().optional(),
      operatorIcao: zod.string().optional(),
      owner: zod.string().optional(),
      registration: zod.string().optional(),
      typeCode: zod
        .string()
        .optional()
        .describe("ICAO aircraft type designator."),
    })
    .optional(),
  state: zod
    .object({
      baroAltM: zod
        .number()
        .optional()
        .describe("Barometric altitude in metres."),
      callsign: zod
        .string()
        .optional()
        .describe("Callsign as broadcast, trimmed."),
      category: zod
        .enum([
          "unknown",
          "light",
          "small",
          "large",
          "high_vortex_large",
          "heavy",
          "high_performance",
          "rotorcraft",
          "glider",
          "lighter_than_air",
          "parachutist",
          "ultralight",
          "uav",
          "space",
          "emergency_surface",
          "service_surface",
          "obstacle",
        ])
        .describe("ADS-B emitter category."),
      country: zod
        .string()
        .optional()
        .describe("Country of registration inferred from the address."),
      geoAltM: zod
        .number()
        .optional()
        .describe("Geometric altitude in metres."),
      headingDeg: zod
        .number()
        .optional()
        .describe("True track in degrees clockwise from north."),
      icao24: zod.string().describe("Mode S address, lower-case hex."),
      lastContact: zod.iso
        .datetime({ offset: true })
        .describe("Time of the last message received from the aircraft."),
      lat: zod
        .number()
        .min(getAircraftResponseStateLatMin)
        .max(getAircraftResponseStateLatMax)
        .describe("WGS-84 latitude in degrees."),
      lon: zod
        .number()
        .min(getAircraftResponseStateLonMin)
        .max(getAircraftResponseStateLonMax)
        .describe("WGS-84 longitude in degrees."),
      onGround: zod
        .boolean()
        .describe("True when the aircraft reports being on the ground."),
      positionAt: zod.iso
        .datetime({ offset: true })
        .describe("Time of the last position report."),
      source: zod
        .enum(["adsb", "asterix", "mlat", "flarm", "unknown"])
        .describe("Surveillance technology that produced the position."),
      squawk: zod.string().optional().describe("Transponder code."),
      velocityMs: zod
        .number()
        .optional()
        .describe("Ground speed in metres per second."),
      vertRateMs: zod
        .number()
        .optional()
        .describe(
          "Vertical rate in metres per second, negative when descending."
        ),
    })
    .optional()
    .describe(
      "Current state, absent when the aircraft is not in the latest snapshot."
    ),
  trail: zod
    .array(
      zod.object({
        baroAltM: zod.number().optional(),
        headingDeg: zod.number().optional(),
        lat: zod.number(),
        lon: zod.number(),
        onGround: zod.boolean(),
        time: zod.iso.datetime({ offset: true }),
      })
    )
    .nullable()
    .describe("Positions in chronological order."),
  trailSource: zod
    .enum(["stored", "opensky", "none"])
    .describe("Origin of the trail points."),
})

/**
 * Thumbnail from Planespotters.net, found by address and then by registration. Images are hotlinked and must be shown with the photographer credit and a link to the photo page.
 * @summary Get a photo of an aircraft
 */
export const getAircraftPhotoPathIcao24RegExp = new RegExp("^[0-9a-fA-F]{6}$")

export const GetAircraftPhotoParams = zod.object({
  icao24: zod
    .string()
    .regex(getAircraftPhotoPathIcao24RegExp)
    .describe("Mode S address as six hex digits."),
})

export const GetAircraftPhotoResponse = zod.object({
  id: zod.string(),
  large: zod
    .object({
      height: zod.int(),
      src: zod.string(),
      width: zod.int(),
    })
    .describe("About 280 px tall."),
  link: zod
    .string()
    .describe(
      "Photo page on Planespotters.net. The image must link here and credit the photographer."
    ),
  photographer: zod.string(),
  source: zod.enum(["planespotters"]).describe("Site that hosts the photo."),
  thumbnail: zod
    .object({
      height: zod.int(),
      src: zod.string(),
      width: zod.int(),
    })
    .describe("About 200 px wide."),
})

/**
 * Downsampled stored positions of aircraft that flew through the box during the window, for replaying the last hours. Tracks with the most points come first.
 * @summary Get recent tracks in a bounding box
 */
export const getHistoryQueryWestDefault = -180
export const getHistoryQueryWestMin = -180
export const getHistoryQueryWestMax = 180

export const getHistoryQuerySouthDefault = -90
export const getHistoryQuerySouthMin = -90
export const getHistoryQuerySouthMax = 90

export const getHistoryQueryEastDefault = 180
export const getHistoryQueryEastMin = -180
export const getHistoryQueryEastMax = 180

export const getHistoryQueryNorthDefault = 90
export const getHistoryQueryNorthMin = -90
export const getHistoryQueryNorthMax = 90

export const getHistoryQueryMinutesDefault = 60
export const getHistoryQueryMinutesMin = 5
export const getHistoryQueryMinutesMax = 180

export const getHistoryQueryLimitDefault = 300
export const getHistoryQueryLimitMax = 1000

export const GetHistoryQueryParams = zod.object({
  west: zod
    .number()
    .min(getHistoryQueryWestMin)
    .max(getHistoryQueryWestMax)
    .default(getHistoryQueryWestDefault)
    .describe(
      "Western edge in degrees. Greater than east when the box crosses the antimeridian."
    ),
  south: zod
    .number()
    .min(getHistoryQuerySouthMin)
    .max(getHistoryQuerySouthMax)
    .default(getHistoryQuerySouthDefault)
    .describe("Southern edge in degrees."),
  east: zod
    .number()
    .min(getHistoryQueryEastMin)
    .max(getHistoryQueryEastMax)
    .default(getHistoryQueryEastDefault)
    .describe("Eastern edge in degrees."),
  north: zod
    .number()
    .min(getHistoryQueryNorthMin)
    .max(getHistoryQueryNorthMax)
    .default(getHistoryQueryNorthDefault)
    .describe("Northern edge in degrees."),
  minutes: zod
    .int()
    .min(getHistoryQueryMinutesMin)
    .max(getHistoryQueryMinutesMax)
    .default(getHistoryQueryMinutesDefault)
    .describe("Length of the window ending now."),
  limit: zod
    .int()
    .min(1)
    .max(getHistoryQueryLimitMax)
    .default(getHistoryQueryLimitDefault)
    .describe("Maximum tracks to return."),
})

export const GetHistoryResponse = zod.object({
  count: zod.int().describe("Tracks returned."),
  from: zod.iso.datetime({ offset: true }),
  to: zod.iso.datetime({ offset: true }),
  tracks: zod
    .array(
      zod.object({
        callsign: zod.string().optional(),
        icao24: zod.string(),
        points: zod
          .array(
            zod.object({
              baroAltM: zod.number().optional(),
              headingDeg: zod.number().optional(),
              lat: zod.number(),
              lon: zod.number(),
              onGround: zod.boolean(),
              time: zod.iso.datetime({ offset: true }),
            })
          )
          .nullable()
          .describe("Chronological positions."),
      })
    )
    .nullable(),
})
