/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const getAirportPathCodeRegExp = new RegExp("^[A-Za-z0-9]{3,4}$")

export const GetAirportParams = zod.object({
  code: zod
    .string()
    .regex(getAirportPathCodeRegExp)
    .describe("ICAO ident or IATA code."),
})

export const GetAirportResponse = zod.object({
  country: zod.string().optional().describe("ISO 3166-1 alpha-2 code."),
  elevationFt: zod.int().optional(),
  iata: zod.string().optional(),
  icao: zod.string().describe("ICAO identifier."),
  lat: zod.number(),
  lon: zod.number(),
  municipality: zod.string().optional(),
  name: zod.string(),
  type: zod
    .string()
    .optional()
    .describe("OurAirports type such as large_airport."),
})
