/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * Live state, airline, route and aircraft for a callsign. Route data comes from adsbdb.
 * @summary Get a flight by callsign
 */
export const getFlightPathCallsignRegExp = new RegExp("^[A-Za-z0-9]{2,8}$")

export const GetFlightParams = zod.object({
  callsign: zod
    .string()
    .regex(getFlightPathCallsignRegExp)
    .describe("ICAO callsign such as DLH2AB."),
})

export const getFlightResponseLiveLatMin = -90
export const getFlightResponseLiveLatMax = 90

export const getFlightResponseLiveLonMin = -180
export const getFlightResponseLiveLonMax = 180

export const GetFlightResponse = zod.object({
  aircraft: zod
    .object({
      icao24: zod.string(),
      manufacturer: zod.string().optional(),
      model: zod.string().optional(),
      operator: zod.string().optional(),
      operatorIcao: zod.string().optional(),
      owner: zod.string().optional(),
      registration: zod.string().optional(),
      typeCode: zod
        .string()
        .optional()
        .describe("ICAO aircraft type designator."),
    })
    .optional(),
  airline: zod
    .object({
      callsign: zod.string().optional(),
      country: zod.string().optional(),
      iata: zod.string().optional(),
      icao: zod.string(),
      name: zod.string(),
    })
    .optional(),
  callsign: zod.string(),
  live: zod
    .object({
      baroAltM: zod
        .number()
        .optional()
        .describe("Barometric altitude in metres."),
      callsign: zod
        .string()
        .optional()
        .describe("Callsign as broadcast, trimmed."),
      category: zod
        .enum([
          "unknown",
          "light",
          "small",
          "large",
          "high_vortex_large",
          "heavy",
          "high_performance",
          "rotorcraft",
          "glider",
          "lighter_than_air",
          "parachutist",
          "ultralight",
          "uav",
          "space",
          "emergency_surface",
          "service_surface",
          "obstacle",
        ])
        .describe("ADS-B emitter category."),
      country: zod
        .string()
        .optional()
        .describe("Country of registration inferred from the address."),
      geoAltM: zod
        .number()
        .optional()
        .describe("Geometric altitude in metres."),
      headingDeg: zod
        .number()
        .optional()
        .describe("True track in degrees clockwise from north."),
      icao24: zod.string().describe("Mode S address, lower-case hex."),
      lastContact: zod.iso
        .datetime({ offset: true })
        .describe("Time of the last message received from the aircraft."),
      lat: zod
        .number()
        .min(getFlightResponseLiveLatMin)
        .max(getFlightResponseLiveLatMax)
        .describe("WGS-84 latitude in degrees."),
      lon: zod
        .number()
        .min(getFlightResponseLiveLonMin)
        .max(getFlightResponseLiveLonMax)
        .describe("WGS-84 longitude in degrees."),
      onGround: zod
        .boolean()
        .describe("True when the aircraft reports being on the ground."),
      positionAt: zod.iso
        .datetime({ offset: true })
        .describe("Time of the last position report."),
      source: zod
        .enum(["adsb", "asterix", "mlat", "flarm", "unknown"])
        .describe("Surveillance technology that produced the position."),
      squawk: zod.string().optional().describe("Transponder code."),
      velocityMs: zod
        .number()
        .optional()
        .describe("Ground speed in metres per second."),
      vertRateMs: zod
        .number()
        .optional()
        .describe(
          "Vertical rate in metres per second, negative when descending."
        ),
    })
    .optional()
    .describe("Current state when the callsign is airborne."),
  route: zod
    .object({
      destination: zod
        .object({
          country: zod.string().optional().describe("ISO 3166-1 alpha-2 code."),
          elevationFt: zod.int().optional(),
          iata: zod.string().optional(),
          icao: zod.string().describe("ICAO identifier."),
          lat: zod.number(),
          lon: zod.number(),
          municipality: zod.string().optional(),
          name: zod.string(),
          type: zod
            .string()
            .optional()
            .describe("OurAirports type such as large_airport."),
        })
        .optional(),
      origin: zod
        .object({
          country: zod.string().optional().describe("ISO 3166-1 alpha-2 code."),
          elevationFt: zod.int().optional(),
          iata: zod.string().optional(),
          icao: zod.string().describe("ICAO identifier."),
          lat: zod.number(),
          lon: zod.number(),
          municipality: zod.string().optional(),
          name: zod.string(),
          type: zod
            .string()
            .optional()
            .describe("OurAirports type such as large_airport."),
        })
        .optional(),
      source: zod
        .enum(["adsbdb", "aviationstack"])
        .describe("Upstream that produced the metadata."),
    })
    .optional(),
})

/**
 * Departure and arrival times from aviationstack. A cache miss spends one request from a small monthly budget, so call it only on demand.
 * @summary Get the schedule of a flight
 */
export const getFlightSchedulePathCallsignRegExp = new RegExp(
  "^[A-Za-z0-9]{2,8}$"
)

export const GetFlightScheduleParams = zod.object({
  callsign: zod
    .string()
    .regex(getFlightSchedulePathCallsignRegExp)
    .describe("ICAO callsign such as DLH2AB."),
})

export const GetFlightScheduleResponse = zod.object({
  airline: zod
    .object({
      callsign: zod.string().optional(),
      country: zod.string().optional(),
      iata: zod.string().optional(),
      icao: zod.string(),
      name: zod.string(),
    })
    .optional(),
  arrival: zod.object({
    actual: zod.iso.datetime({ offset: true }).optional(),
    airport: zod.string().optional(),
    delayMin: zod.int().optional().describe("Delay in minutes."),
    estimated: zod.iso.datetime({ offset: true }).optional(),
    gate: zod.string().optional(),
    iata: zod.string().optional(),
    icao: zod.string().optional(),
    scheduled: zod.iso.datetime({ offset: true }).optional(),
    terminal: zod.string().optional(),
    timezone: zod.string().optional(),
  }),
  callsign: zod.string(),
  departure: zod.object({
    actual: zod.iso.datetime({ offset: true }).optional(),
    airport: zod.string().optional(),
    delayMin: zod.int().optional().describe("Delay in minutes."),
    estimated: zod.iso.datetime({ offset: true }).optional(),
    gate: zod.string().optional(),
    iata: zod.string().optional(),
    icao: zod.string().optional(),
    scheduled: zod.iso.datetime({ offset: true }).optional(),
    terminal: zod.string().optional(),
    timezone: zod.string().optional(),
  }),
  fetchedAt: zod.iso
    .datetime({ offset: true })
    .describe("When the data was fetched from aviationstack."),
  flightDate: zod.string().describe("Departure date in YYYY-MM-DD."),
  flightIata: zod.string().optional(),
  flightIcao: zod.string().optional(),
  registration: zod.string().optional(),
  source: zod
    .enum(["adsbdb", "aviationstack"])
    .describe("Upstream that produced the metadata."),
  status: zod
    .enum([
      "scheduled",
      "active",
      "landed",
      "cancelled",
      "incident",
      "diverted",
      "unknown",
    ])
    .describe("Schedule status of a flight."),
})
