/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import type { Airport, ErrorModel } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getGetAirportUrl = (code: string) => {
  return `/airports/${code}`
}

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const getAirport = async (
  code: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<Airport> => {
  return bffFetch<Airport>(getGetAirportUrl(code), {
    ...options,
    method: "GET",
  })
}

export const getGetAirportMutationKey = () => ["getAirport"] as const

export const getGetAirportMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAirport>>,
    TError,
    GetAirportMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAirport>>,
  TError,
  GetAirportMutationVariables,
  TContext
> => {
  const mutationKey = getGetAirportMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAirport>>,
    GetAirportMutationVariables
  > = (props) => {
    const { code } = props ?? {}

    return getAirport(code, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetAirportMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAirport>>
>

export type GetAirportMutationError = ErrorModel
export type GetAirportMutationVariables = { code: string }

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const useGetAirport = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getAirport>>,
      TError,
      GetAirportMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getAirport>>,
  TError,
  GetAirportMutationVariables,
  TContext
> => {
  return useMutation(getGetAirportMutationOptions(options), queryClient)
}
