/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import type { Airport, ErrorModel } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const getGetAirportUrl = (code: string) => {
  return `/airports/${code}`
}

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const getAirport = async (
  code: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<Airport> => {
  return bffFetch<Airport>(getGetAirportUrl(code), {
    ...options,
    method: "GET",
  })
}

export const getGetAirportInfiniteQueryKey = (code: string) => {
  return ["infinite", `/airports/${code}`] as const
}

export const getGetAirportQueryKey = (code: string) => {
  return [`/airports/${code}`] as const
}

export const getGetAirportInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAirport>>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAirportInfiniteQueryKey(code)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAirport>>> = ({
    signal,
  }) => getAirport(code, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: code !== null && code !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAirport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAirportInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAirport>>
>
export type GetAirportInfiniteQueryError = ErrorModel

export function useGetAirportInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirport>>>,
  TError = ErrorModel,
>(
  code: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirport>>,
          TError,
          Awaited<ReturnType<typeof getAirport>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirportInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirport>>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirport>>,
          TError,
          Awaited<ReturnType<typeof getAirport>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirportInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirport>>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an airport by ICAO or IATA code
 */

export function useGetAirportInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAirport>>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAirportInfiniteQueryOptions(code, options)

  const query = useInfiniteQuery(
    queryOptions,
    queryClient
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const prefetchGetAirportInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  code: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAirport>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetAirportInfiniteQueryOptions(code, options)

  await queryClient.prefetchInfiniteQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useGetAirportInfinite} query
 */
export const invalidateGetAirportInfinite = async (
  queryClient: QueryClient,
  code: string,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getGetAirportInfiniteQueryKey(code) },
    options
  )

  return queryClient
}

export const getGetAirportQueryOptions = <
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAirportQueryKey(code)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAirport>>> = ({
    signal,
  }) => getAirport(code, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: code !== null && code !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAirport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAirportQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAirport>>
>
export type GetAirportQueryError = ErrorModel

export function useGetAirport<
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  code: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirport>>,
          TError,
          Awaited<ReturnType<typeof getAirport>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirport<
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAirport>>,
          TError,
          Awaited<ReturnType<typeof getAirport>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAirport<
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an airport by ICAO or IATA code
 */

export function useGetAirport<
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAirportQueryOptions(code, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get an airport by ICAO or IATA code
 */
export const prefetchGetAirportQuery = async <
  TData = Awaited<ReturnType<typeof getAirport>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAirport>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetAirportQueryOptions(code, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useGetAirport} query
 */
export const invalidateGetAirport = async (
  queryClient: QueryClient,
  code: string,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getGetAirportQueryKey(code) },
    options
  )

  return queryClient
}
