/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Aircraft } from "./aircraft.ts"
import type { AircraftInfo } from "./aircraftInfo.ts"
import type { TrailPoint } from "./trailPoint.ts"
import type { TrailSource } from "./trailSource.ts"

export interface AircraftDetail {
  icao24: string
  info?: AircraftInfo
  /** Current state, absent when the aircraft is not in the latest snapshot. */
  state?: Aircraft
  /**
   * Positions in chronological order.
   * @nullable
   */
  trail: TrailPoint[] | null
  trailSource: TrailSource
}
