/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Aircraft } from "./aircraft.ts"

export interface AircraftList {
  /** Seconds between the snapshot time and the response. */
  ageSeconds: number
  /** @nullable */
  aircraft: Aircraft[] | null
  /** Aircraft returned. */
  count: number
  /** True when the snapshot is older than the freshness limit, for example while the poller is out of credits. */
  stale: boolean
  /** Snapshot time. */
  time: string
  /** Aircraft inside the bounds before thinning. */
  total: number
}
