/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface AircraftInfo {
  icao24: string
  manufacturer?: string
  model?: string
  operator?: string
  operatorIcao?: string
  owner?: string
  registration?: string
  /** ICAO aircraft type designator. */
  typeCode?: string
}
