/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Category } from "./category.ts"
import type { PositionSource } from "./positionSource.ts"

export interface Aircraft {
  /** Barometric altitude in metres. */
  baroAltM?: number
  /** Callsign as broadcast, trimmed. */
  callsign?: string
  category: Category
  /** Country of registration inferred from the address. */
  country?: string
  /** Geometric altitude in metres. */
  geoAltM?: number
  /** True track in degrees clockwise from north. */
  headingDeg?: number
  /** Mode S address, lower-case hex. */
  icao24: string
  /** Time of the last message received from the aircraft. */
  lastContact: string
  /**
   * WGS-84 latitude in degrees.
   * @minimum -90
   * @maximum 90
   */
  lat: number
  /**
   * WGS-84 longitude in degrees.
   * @minimum -180
   * @maximum 180
   */
  lon: number
  /** True when the aircraft reports being on the ground. */
  onGround: boolean
  /** Time of the last position report. */
  positionAt: string
  source: PositionSource
  /** Transponder code. */
  squawk?: string
  /** Ground speed in metres per second. */
  velocityMs?: number
  /** Vertical rate in metres per second, negative when descending. */
  vertRateMs?: number
}
