/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface Airline {
  callsign?: string
  country?: string
  iata?: string
  icao: string
  name: string
}
