/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface Airport {
  /** ISO 3166-1 alpha-2 code. */
  country?: string
  elevationFt?: number
  iata?: string
  /** ICAO identifier. */
  icao: string
  lat: number
  lon: number
  municipality?: string
  name: string
  /** OurAirports type such as large_airport. */
  type?: string
}
