/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Airport } from "./airport.ts"

export interface AirportList {
  /** @nullable */
  airports: Airport[] | null
  count: number
}
