/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface CacheStats {
  /** Entries currently in the in-process tier. */
  l1Entries: number
  /** Hits in the in-process tier. */
  l1Hits: number
  /** Hits in Redis. */
  l2Hits: number
  /** Loads from the source. */
  misses: number
}
