/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * ADS-B emitter category.
 */
export type Category = (typeof Category)[keyof typeof Category]

export const Category = {
  unknown: "unknown",
  light: "light",
  small: "small",
  large: "large",
  high_vortex_large: "high_vortex_large",
  heavy: "heavy",
  high_performance: "high_performance",
  rotorcraft: "rotorcraft",
  glider: "glider",
  lighter_than_air: "lighter_than_air",
  parachutist: "parachutist",
  ultralight: "ultralight",
  uav: "uav",
  space: "space",
  emergency_surface: "emergency_surface",
  service_surface: "service_surface",
  obstacle: "obstacle",
} as const
