/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Aircraft } from "./aircraft.ts"
import type { AircraftInfo } from "./aircraftInfo.ts"
import type { Airline } from "./airline.ts"
import type { Route } from "./route.ts"

export interface FlightDetail {
  aircraft?: AircraftInfo
  airline?: Airline
  callsign: string
  /** Current state when the callsign is airborne. */
  live?: Aircraft
  route?: Route
}
