/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Schedule status of a flight.
 */
export type FlightStatus = (typeof FlightStatus)[keyof typeof FlightStatus]

export const FlightStatus = {
  scheduled: "scheduled",
  active: "active",
  landed: "landed",
  cancelled: "cancelled",
  incident: "incident",
  diverted: "diverted",
  unknown: "unknown",
} as const
