/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export type GetHistoryParams = {
  /**
   * Western edge in degrees. Greater than east when the box crosses the antimeridian.
   * @minimum -180
   * @maximum 180
   */
  west?: number
  /**
   * Southern edge in degrees.
   * @minimum -90
   * @maximum 90
   */
  south?: number
  /**
   * Eastern edge in degrees.
   * @minimum -180
   * @maximum 180
   */
  east?: number
  /**
   * Northern edge in degrees.
   * @minimum -90
   * @maximum 90
   */
  north?: number
  /**
   * Length of the window ending now.
   * @minimum 5
   * @maximum 180
   */
  minutes?: number
  /**
   * Maximum tracks to return.
   * @minimum 1
   * @maximum 1000
   */
  limit?: number
}
