/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Track } from "./track.ts"

export interface History {
  /** Tracks returned. */
  count: number
  from: string
  to: string
  /** @nullable */
  tracks: Track[] | null
}
