/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Upstream that produced the metadata.
 */
export type MetaSource = (typeof MetaSource)[keyof typeof MetaSource]

export const MetaSource = {
  adsbdb: "adsbdb",
  aviationstack: "aviationstack",
} as const
