/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { PhotoImage } from "./photoImage.ts"
import type { PhotoSource } from "./photoSource.ts"

export interface Photo {
  id: string
  /** About 280 px tall. */
  large: PhotoImage
  /** Photo page on Planespotters.net. The image must link here and credit the photographer. */
  link: string
  photographer: string
  source: PhotoSource
  /** About 200 px wide. */
  thumbnail: PhotoImage
}
