/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Site that hosts the photo.
 */
export type PhotoSource = (typeof PhotoSource)[keyof typeof PhotoSource]

export const PhotoSource = {
  planespotters: "planespotters",
} as const
