/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { PollerMode } from "./pollerMode.ts"

export interface PollerStatus {
  /** OpenSky credits left today. */
  creditsRemaining: number
  creditsUsedToday: number
  /** Current poll interval. */
  intervalSeconds: number
  lastError?: string
  lastPoll?: string
  /** True when this instance runs the poller. */
  leader: boolean
  mode: PollerMode
  nextPoll?: string
}
