/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { PollerMode } from "./pollerMode.ts"

export interface PollerStatus {
  /** Requests allowed per UTC day before the poller pauses. */
  dailyCap: number
  /** Target age of the area viewers are looking at. */
  intervalSeconds: number
  lastError?: string
  lastPoll?: string
  /** True when this instance runs the poller. */
  leader: boolean
  mode: PollerMode
  nextPoll?: string
  /** Upstream requests made since UTC midnight. */
  requestsToday: number
  /** Circles in the background world sweep. */
  sweepCells: number
  /** Circles currently covering viewer viewports. */
  viewCells: number
}
