/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Poller state. Active while viewers are connected, idle otherwise, paused when out of credits, follower when another instance polls.
 */
export type PollerMode = (typeof PollerMode)[keyof typeof PollerMode]

export const PollerMode = {
  active: "active",
  idle: "idle",
  paused: "paused",
  follower: "follower",
  disabled: "disabled",
} as const
