/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Surveillance technology that produced the position.
 */
export type PositionSource =
  (typeof PositionSource)[keyof typeof PositionSource]

export const PositionSource = {
  adsb: "adsb",
  asterix: "asterix",
  mlat: "mlat",
  flarm: "flarm",
  unknown: "unknown",
} as const
