/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface QuotaStatus {
  cap: number
  enabled: boolean
  /** Month in YYYY-MM. */
  period: string
  used: number
}
