/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Airline } from "./airline.ts"
import type { FlightStatus } from "./flightStatus.ts"
import type { MetaSource } from "./metaSource.ts"
import type { ScheduleEndpoint } from "./scheduleEndpoint.ts"

export interface Schedule {
  airline?: Airline
  arrival: ScheduleEndpoint
  callsign: string
  departure: ScheduleEndpoint
  /** When the data was fetched from aviationstack. */
  fetchedAt: string
  /** Departure date in YYYY-MM-DD. */
  flightDate: string
  flightIata?: string
  flightIcao?: string
  registration?: string
  source: MetaSource
  status: FlightStatus
}
