/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { Aircraft } from "./aircraft.ts"
import type { Airline } from "./airline.ts"
import type { Airport } from "./airport.ts"

export interface SearchResult {
  /**
   * Airborne matches by callsign, address or registration.
   * @nullable
   */
  aircraft: Aircraft[] | null
  /** @nullable */
  airlines: Airline[] | null
  /** @nullable */
  airports: Airport[] | null
}
