/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export type SearchParams = {
  /**
   * Callsign, address, registration, airport or airline text.
   * @minLength 2
   * @maxLength 40
   */
  q: string
}
