/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { CacheStats } from "./cacheStats.ts"
import type { PollerStatus } from "./pollerStatus.ts"
import type { QuotaStatus } from "./quotaStatus.ts"

export interface Stats {
  aircraftCount: number
  aviationstack: QuotaStatus
  cache: CacheStats
  poller: PollerStatus
  snapshotAgeSeconds: number
  snapshotTime?: string
  /** True when the snapshot is older than the freshness limit. */
  stale: boolean
  version: string
  /** Open live connections on this instance. */
  viewers: number
}
