/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import type { TrailPoint } from "./trailPoint.ts"

export interface Track {
  callsign?: string
  icao24: string
  /**
   * Chronological positions.
   * @nullable
   */
  points: TrailPoint[] | null
}
