/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

export interface TrailPoint {
  baroAltM?: number
  headingDeg?: number
  lat: number
  lon: number
  onGround: boolean
  time: string
}
