/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */

/**
 * Origin of the trail points.
 */
export type TrailSource = (typeof TrailSource)[keyof typeof TrailSource]

export const TrailSource = {
  stored: "stored",
  opensky: "opensky",
  none: "none",
} as const
