/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import * as zod from "zod"

/**
 * @summary Search aircraft, airports and airlines
 */
export const searchQueryQMin = 2
export const searchQueryQMax = 40

export const SearchQueryParams = zod.object({
  q: zod
    .string()
    .min(searchQueryQMin)
    .max(searchQueryQMax)
    .describe("Callsign, address, registration, airport or airline text."),
})

export const searchResponseAircraftItemLatMin = -90
export const searchResponseAircraftItemLatMax = 90

export const searchResponseAircraftItemLonMin = -180
export const searchResponseAircraftItemLonMax = 180

export const SearchResponse = zod.object({
  aircraft: zod
    .array(
      zod.object({
        baroAltM: zod
          .number()
          .optional()
          .describe("Barometric altitude in metres."),
        callsign: zod
          .string()
          .optional()
          .describe("Callsign as broadcast, trimmed."),
        category: zod
          .enum([
            "unknown",
            "light",
            "small",
            "large",
            "high_vortex_large",
            "heavy",
            "high_performance",
            "rotorcraft",
            "glider",
            "lighter_than_air",
            "parachutist",
            "ultralight",
            "uav",
            "space",
            "emergency_surface",
            "service_surface",
            "obstacle",
          ])
          .describe("ADS-B emitter category."),
        country: zod
          .string()
          .optional()
          .describe("Country of registration inferred from the address."),
        geoAltM: zod
          .number()
          .optional()
          .describe("Geometric altitude in metres."),
        headingDeg: zod
          .number()
          .optional()
          .describe("True track in degrees clockwise from north."),
        icao24: zod.string().describe("Mode S address, lower-case hex."),
        lastContact: zod.iso
          .datetime({ offset: true })
          .describe("Time of the last message received from the aircraft."),
        lat: zod
          .number()
          .min(searchResponseAircraftItemLatMin)
          .max(searchResponseAircraftItemLatMax)
          .describe("WGS-84 latitude in degrees."),
        lon: zod
          .number()
          .min(searchResponseAircraftItemLonMin)
          .max(searchResponseAircraftItemLonMax)
          .describe("WGS-84 longitude in degrees."),
        onGround: zod
          .boolean()
          .describe("True when the aircraft reports being on the ground."),
        positionAt: zod.iso
          .datetime({ offset: true })
          .describe("Time of the last position report."),
        source: zod
          .enum(["adsb", "asterix", "mlat", "flarm", "unknown"])
          .describe("Surveillance technology that produced the position."),
        squawk: zod.string().optional().describe("Transponder code."),
        velocityMs: zod
          .number()
          .optional()
          .describe("Ground speed in metres per second."),
        vertRateMs: zod
          .number()
          .optional()
          .describe(
            "Vertical rate in metres per second, negative when descending."
          ),
      })
    )
    .nullable()
    .describe("Airborne matches by callsign, address or registration."),
  airlines: zod
    .array(
      zod.object({
        callsign: zod.string().optional(),
        country: zod.string().optional(),
        iata: zod.string().optional(),
        icao: zod.string(),
        name: zod.string(),
      })
    )
    .nullable(),
  airports: zod
    .array(
      zod.object({
        country: zod.string().optional().describe("ISO 3166-1 alpha-2 code."),
        elevationFt: zod.int().optional(),
        iata: zod.string().optional(),
        icao: zod.string().describe("ICAO identifier."),
        lat: zod.number(),
        lon: zod.number(),
        municipality: zod.string().optional(),
        name: zod.string(),
        type: zod
          .string()
          .optional()
          .describe("OurAirports type such as large_airport."),
      })
    )
    .nullable(),
})
