/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import type { ErrorModel, SearchParams, SearchResult } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getSearchUrl = (params: SearchParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/search?${stringifiedParams}`
    : `/search`
}

/**
 * @summary Search aircraft, airports and airlines
 */
export const search = async (
  params: SearchParams,
  options?: Parameters<typeof bffFetch>[1]
): Promise<SearchResult> => {
  return bffFetch<SearchResult>(getSearchUrl(params), {
    ...options,
    method: "GET",
  })
}

export const getSearchMutationKey = () => ["search"] as const

export const getSearchMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    SearchMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof search>>,
  TError,
  SearchMutationVariables,
  TContext
> => {
  const mutationKey = getSearchMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof search>>,
    SearchMutationVariables
  > = (props) => {
    const { params } = props ?? {}

    return search(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SearchMutationResult = NonNullable<
  Awaited<ReturnType<typeof search>>
>

export type SearchMutationError = ErrorModel
export type SearchMutationVariables = { params: SearchParams }

/**
 * @summary Search aircraft, airports and airlines
 */
export const useSearch = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof search>>,
      TError,
      SearchMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof search>>,
  TError,
  SearchMutationVariables,
  TContext
> => {
  return useMutation(getSearchMutationOptions(options), queryClient)
}
