/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import type { ErrorModel, SearchParams, SearchResult } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const getSearchUrl = (params: SearchParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/search?${stringifiedParams}`
    : `/search`
}

/**
 * @summary Search aircraft, airports and airlines
 */
export const search = async (
  params: SearchParams,
  options?: Parameters<typeof bffFetch>[1]
): Promise<SearchResult> => {
  return bffFetch<SearchResult>(getSearchUrl(params), {
    ...options,
    method: "GET",
  })
}

export const getSearchInfiniteQueryKey = (params?: SearchParams) => {
  return ["infinite", `/search`, ...(params ? [params] : [])] as const
}

export const getSearchQueryKey = (params?: SearchParams) => {
  return [`/search`, ...(params ? [params] : [])] as const
}

export const getSearchInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof search>>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getSearchInfiniteQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({
    signal,
  }) => search(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof search>>
>
export type SearchInfiniteQueryError = ErrorModel

export function useSearchInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof search>>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof search>>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof search>>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search aircraft, airports and airlines
 */

export function useSearchInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof search>>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getSearchInfiniteQueryOptions(params, options)

  const query = useInfiniteQuery(
    queryOptions,
    queryClient
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Search aircraft, airports and airlines
 */
export const prefetchSearchInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  params: SearchParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getSearchInfiniteQueryOptions(params, options)

  await queryClient.prefetchInfiniteQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useSearchInfinite} query
 */
export const invalidateSearchInfinite = async (
  queryClient: QueryClient,
  params: SearchParams,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getSearchInfiniteQueryKey(params) },
    options
  )

  return queryClient
}

export const getSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({
    signal,
  }) => search(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = ErrorModel

export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Search aircraft, airports and airlines
 */

export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  params: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getSearchQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Search aircraft, airports and airlines
 */
export const prefetchSearchQuery = async <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorModel,
>(
  queryClient: QueryClient,
  params: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >
    request?: SecondParameter<typeof bffFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getSearchQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Invalidates the {@link useSearch} query
 */
export const invalidateSearch = async (
  queryClient: QueryClient,
  params: SearchParams,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getSearchQueryKey(params) },
    options
  )

  return queryClient
}
