/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import type { ErrorModel, Stats } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getGetStatsUrl = () => {
  return `/stats`
}

/**
 * @summary Get service status and upstream budgets
 */
export const getStats = async (
  options?: Parameters<typeof bffFetch>[1]
): Promise<Stats> => {
  return bffFetch<Stats>(getGetStatsUrl(), {
    ...options,
    method: "GET",
  })
}

export const getGetStatsMutationKey = () => ["getStats"] as const

export const getGetStatsMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getStats>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getGetStatsMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getStats>>,
    void
  > = () => {
    return getStats(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetStatsMutationResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>

export type GetStatsMutationError = ErrorModel

/**
 * @summary Get service status and upstream budgets
 */
export const useGetStats = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getStats>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getStats>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getGetStatsMutationOptions(options), queryClient)
}
