/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import type { ErrorModel, FlightDetail, Schedule } from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getGetFlightUrl = (callsign: string) => {
  return `/flights/${callsign}`
}

/**
 * Live state, airline, route and aircraft for a callsign. Route data comes from adsbdb.
 * @summary Get a flight by callsign
 */
export const getFlight = async (
  callsign: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<FlightDetail> => {
  return bffFetch<FlightDetail>(getGetFlightUrl(callsign), {
    ...options,
    method: "GET",
  })
}

export const getGetFlightMutationKey = () => ["getFlight"] as const

export const getGetFlightMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getFlight>>,
    TError,
    GetFlightMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getFlight>>,
  TError,
  GetFlightMutationVariables,
  TContext
> => {
  const mutationKey = getGetFlightMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getFlight>>,
    GetFlightMutationVariables
  > = (props) => {
    const { callsign } = props ?? {}

    return getFlight(callsign, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetFlightMutationResult = NonNullable<
  Awaited<ReturnType<typeof getFlight>>
>

export type GetFlightMutationError = ErrorModel
export type GetFlightMutationVariables = { callsign: string }

/**
 * @summary Get a flight by callsign
 */
export const useGetFlight = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getFlight>>,
      TError,
      GetFlightMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getFlight>>,
  TError,
  GetFlightMutationVariables,
  TContext
> => {
  return useMutation(getGetFlightMutationOptions(options), queryClient)
}
export const getGetFlightScheduleUrl = (callsign: string) => {
  return `/flights/${callsign}/schedule`
}

/**
 * Departure and arrival times from aviationstack. A cache miss spends one request from a small monthly budget, so call it only on demand.
 * @summary Get the schedule of a flight
 */
export const getFlightSchedule = async (
  callsign: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<Schedule> => {
  return bffFetch<Schedule>(getGetFlightScheduleUrl(callsign), {
    ...options,
    method: "GET",
  })
}

export const getGetFlightScheduleMutationKey = () =>
  ["getFlightSchedule"] as const

export const getGetFlightScheduleMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getFlightSchedule>>,
    TError,
    GetFlightScheduleMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getFlightSchedule>>,
  TError,
  GetFlightScheduleMutationVariables,
  TContext
> => {
  const mutationKey = getGetFlightScheduleMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getFlightSchedule>>,
    GetFlightScheduleMutationVariables
  > = (props) => {
    const { callsign } = props ?? {}

    return getFlightSchedule(callsign, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetFlightScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof getFlightSchedule>>
>

export type GetFlightScheduleMutationError = ErrorModel
export type GetFlightScheduleMutationVariables = { callsign: string }

/**
 * @summary Get the schedule of a flight
 */
export const useGetFlightSchedule = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getFlightSchedule>>,
      TError,
      GetFlightScheduleMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getFlightSchedule>>,
  TError,
  GetFlightScheduleMutationVariables,
  TContext
> => {
  return useMutation(getGetFlightScheduleMutationOptions(options), queryClient)
}
