/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flightpath API
 * Live aircraft positions from the OpenSky Network with flight, airport and airline metadata.
 * OpenAPI spec version: dev
 */
import { useMutation } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query"

import type {
  AircraftDetail,
  AircraftList,
  ErrorModel,
  ListAircraftParams,
} from "../schemas"

import { bffFetch } from "../../server/bff-fetch.ts"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getListAircraftUrl = (params?: ListAircraftParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/aircraft?${stringifiedParams}`
    : `/aircraft`
}

/**
 * Current positions from the latest snapshot. When more than limit aircraft are inside the box the result is thinned to a stable subset.
 * @summary List aircraft in a bounding box
 */
export const listAircraft = async (
  params?: ListAircraftParams,
  options?: Parameters<typeof bffFetch>[1]
): Promise<AircraftList> => {
  return bffFetch<AircraftList>(getListAircraftUrl(params), {
    ...options,
    method: "GET",
  })
}

export const getListAircraftMutationKey = () => ["listAircraft"] as const

export const getListAircraftMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof listAircraft>>,
    TError,
    ListAircraftMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof listAircraft>>,
  TError,
  ListAircraftMutationVariables,
  TContext
> => {
  const mutationKey = getListAircraftMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof listAircraft>>,
    ListAircraftMutationVariables
  > = (props) => {
    const { params } = props ?? {}

    return listAircraft(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ListAircraftMutationResult = NonNullable<
  Awaited<ReturnType<typeof listAircraft>>
>

export type ListAircraftMutationError = ErrorModel
export type ListAircraftMutationVariables = { params?: ListAircraftParams }

/**
 * @summary List aircraft in a bounding box
 */
export const useListAircraft = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof listAircraft>>,
      TError,
      ListAircraftMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof listAircraft>>,
  TError,
  ListAircraftMutationVariables,
  TContext
> => {
  return useMutation(getListAircraftMutationOptions(options), queryClient)
}
export const getGetAircraftUrl = (icao24: string) => {
  return `/aircraft/${icao24}`
}

/**
 * @summary Get one aircraft with its recent trail
 */
export const getAircraft = async (
  icao24: string,
  options?: Parameters<typeof bffFetch>[1]
): Promise<AircraftDetail> => {
  return bffFetch<AircraftDetail>(getGetAircraftUrl(icao24), {
    ...options,
    method: "GET",
  })
}

export const getGetAircraftMutationKey = () => ["getAircraft"] as const

export const getGetAircraftMutationOptions = <
  TError = ErrorModel,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAircraft>>,
    TError,
    GetAircraftMutationVariables,
    TContext
  >
  request?: SecondParameter<typeof bffFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAircraft>>,
  TError,
  GetAircraftMutationVariables,
  TContext
> => {
  const mutationKey = getGetAircraftMutationKey()
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAircraft>>,
    GetAircraftMutationVariables
  > = (props) => {
    const { icao24 } = props ?? {}

    return getAircraft(icao24, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetAircraftMutationResult = NonNullable<
  Awaited<ReturnType<typeof getAircraft>>
>

export type GetAircraftMutationError = ErrorModel
export type GetAircraftMutationVariables = { icao24: string }

/**
 * @summary Get one aircraft with its recent trail
 */
export const useGetAircraft = <TError = ErrorModel, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getAircraft>>,
      TError,
      GetAircraftMutationVariables,
      TContext
    >
    request?: SecondParameter<typeof bffFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getAircraft>>,
  TError,
  GetAircraftMutationVariables,
  TContext
> => {
  return useMutation(getGetAircraftMutationOptions(options), queryClient)
}
